name: 'Setup environment'
description: 'Sets up environment and loads dependencies'
runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: 18
    - name: Load cache
      uses: actions/cache/restore@v4
      with:
        path: |
          node_modules
        key: node_modules-${{ github.run_id }}
